version: '3'
services:
        service-user:
                build:
                        context: ./UserController
                        dockerfile: Dockerfile
                container_name: service-user
                networks:
                        - app-network
                depends_on:
                        - db-user
                ports:
                        - "8003:8003"
        service-card:
                build:
                        context: ./CardController
                        dockerfile: Dockerfile
                container_name: service-card
                networks:
                        - app-network
                depends_on:
                        - db-card
                ports:
                        - "8000:8000"
        service-game:
                build:
                        context: ./GameController
                        dockerfile: Dockerfile
                container_name: service-game
                networks:
                        - app-network
                depends_on:
                        - db-game
                ports:
                        - "8001:8001"
        service-store:
                build:
                        context: ./TransactionController
                        dockerfile: Dockerfile
                container_name: service-store
                networks:
                        - app-network
                depends_on:
                        - db-store
                ports:
                        - "8002:8002"
        nginx-reverse-proxy:
            image: nginx:latest
            container_name: reverse_proxy
            volumes:
                    - ./nginx.conf:/etc/nginx/nginx.conf
            ports:
                    - "80:80"
            depends_on:
                    - service-user
                    - service-card
                    - service-game
                    - service-store
                    - nginx-front
            networks:
                    - app-network
        nginx-front:
            image: nginx:latest
            container_name: front
            volumes:
                    - ./front/nginx.conf:/etc/nginx/nginx.conf
                    - ./front/website:/etc/nginx/html
            expose:
                    - "8080"
            networks:
                    - app-network
        db-card:
                image: postgres:14
                restart: always
                container_name: db-card
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: admin
                        POSTGRES_DB: CardGameCard
                networks:
                        - app-network
                ports:
                - "5450:5432"
        db-user:
                image: postgres:14
                restart: always
                container_name: db-user
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: admin
                        POSTGRES_DB: CardGameUser
                networks:
                        - app-network
                ports:
                - "5451:5432"
        db-game:
                image: postgres:14
                restart: always
                container_name: db-game
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: admin
                        POSTGRES_DB: CardGameGame
                networks:
                        - app-network
                ports:
                - "5452:5432"
        db-store:
                image: postgres:14
                restart: always
                container_name: db-store
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: admin
                        POSTGRES_DB: CardGameTransaction
                networks:
                        - app-network
                ports:
                - "5453:5432"

networks:
    app-network: