version: '3'
services:
        service-user:
                build:
                        context: ./UserController
                        dockerfile: Dockerfile
                container_name: service-user
                networks:
                        - app-network
                depends_on:
                        - db-user
        service-card:
                build:
                        context: ./CardController
                        dockerfile: Dockerfile
                container_name: service-card
                networks:
                        - app-network
                depends_on:
                        - db-card
        service-game:
                build:
                        context: ./GameController
                        dockerfile: Dockerfile
                container_name: service-game
                networks:
                        - app-network
                depends_on:
                        - db-game
        service-transaction:
                build:
                        context: ./TransactionController
                        dockerfile: Dockerfile
                container_name: service-transaction
                networks:
                        - app-network
                depends_on:
                        - db-store
        nginx-reverse-proxy:
            image: nginx:latest
            container_name: reverse_proxy
            volumes:
                    - ./nginx.conf:/etc/nginx/nginx.conf
            ports:
                    - "80:80"
            depends_on:
                    - service-user
                    - service-card
                    - service-game
                    - service-transaction
                    - nginx-front
            networks:
                    - app-network
        nginx-front:
            image: nginx:latest
            container_name: front
            volumes:
                    - ./front/nginx.conf:/etc/nginx/nginx.conf
                    - ./front/website:/etc/nginx/html
            expose:
                    - "8080"
            networks:
                    - app-network
        db-card:
                image: postgres
                restart: always
                container_name: db-card
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: admin
                volumes:
                - ./card.sql:/docker-entrypoint-initdb.d/card.sql # Mount SQL script for db-card
                command: postgres -d postgres -U postgres -f /docker-entrypoint-initdb.d/card.sql # Execute SQL script

        db-user:
                image: postgres
                restart: always
                container_name: db-user
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: admin
                volumes:
                - ./user.sql:/docker-entrypoint-initdb.d/user.sql # Mount SQL script for db-card
                command: postgres -d postgres -U postgres -f /docker-entrypoint-initdb.d/user.sql # Execute SQL script
        db-game:
                image: postgres
                restart: always
                container_name: db-game
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: admin
                volumes:
                - ./game.sql:/docker-entrypoint-initdb.d/game.sql # Mount SQL script for db-card
                command: postgres -d postgres -U postgres -f /docker-entrypoint-initdb.d/game.sql # Execute SQL script
        db-store:
                image: postgres
                restart: always
                container_name: db-store
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: admin
                volumes:
                - ./store.sql:/docker-entrypoint-initdb.d/store.sql # Mount SQL script for db-card
                command: postgres -d postgres -U postgres -f /docker-entrypoint-initdb.d/store.sql # Execute SQL script

networks:
    app-network: